name: Build and Publish

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish /p:PublishProfile=ClickOnceProfile

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PublishedApp
          path: ./publish
