name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build NagMe/NagMe.csproj --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish NagMe/NagMe.csproj --configuration Release --no-build -p:PublishProfile=FolderProfile

      - name: Build Installer
        run: dotnet build Installer/Installer.wixproj --configuration Debug --no-restore

      - name: Package Installer Files
        run: |
          cd Installer/bin/Debug/en-US
          Compress-Archive -Path 'Installer.msi','cab1.cab' -DestinationPath 'Installer.zip'

      - name: Create Release
        uses: ncipollo/release-action@v1  
        with:
          artifacts: "Installer/bin/Debug/en-US/Installer.zip"
          bodyFile: "ReleaseNotes/${{ env.RELEASE_VERSION }}.md"
          draft: false
          prerelease: false
